### ISSUE TITLE
Swap "corestore-swarm-networking" for "@corestore/networker"

### ISSUE THREAD

**Issue by voxpelli** [Sydsvenskan/hyperseed#4]
It has changed name twice: https://github.com/andrewosh/corestore-networker/commit/aa67287e3404188f432b121c15e5fc459c7ef157

**Comment by voxpelli** [comment]
Upgrade is described in: https://github.com/andrewosh/corestore-networker/blob/master/UPGRADE.md

**Comment by digli** [comment]
Fixed by 14cadd85e16f4f18926ae647b24b671da47a352e
